version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=739421303208.dkr.ecr.us-east-1.amazonaws.com/image_repo_name
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t image_repo_name .
      - docker tag image_repo_name:latest 739421303208.dkr.ecr.us-east-1.amazonaws.com/image_repo_name:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 739421303208.dkr.ecr.us-east-1.amazonaws.com/image_repo_name:latest
      - docker push image_repo_name:latest 739421303208.dkr.ecr.us-east-1.amazonaws.com/image_repo_name:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "739421303208.dkr.ecr.us-east-1.amazonaws.com/image_repo_name:image_repo_name" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
